import { Inter } from "next/font/google";
import MainNav from "@/components/NavBar/MainNav";
import AuthProvider from "./auth-context";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <AuthProvider>
            <MainNav />
            {children}
          </AuthProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
